### ISSUE TITLE
help

### ISSUE THREAD

**Issue by xuxu865** [extatent/Discord-QR-Token-Grabber#2]
how do we build this

**Comment by extatent** [comment]
Install [Visual Studio 2022](https://visualstudio.microsoft.com/) and [.NET 6 SDK](https://dotnet.microsoft.com/en-us/download/dotnet/6.0). After that, open the Solution file (.sln) or C# Project file (.csproj). On the menu bar, choose Build > Build Solution (CTRL+SHIFT+B).
