### ISSUE TITLE
QR code not created

### ISSUE THREAD

**Issue by NickTziavas** [extatent/Discord-QR-Token-Grabber#4]
Hey,i installed the chrome version it needs,but when chrome opens it asks me for my discord email and pass.When i put it,chrome closes and QR Stealer says error "Couldnt make/generate QR Code.Could i have some help please?

**Comment by extatent** [comment]
You don't need to enter your own login credentials, Read the [usage](https://github.com/extatent/Discord-QR-Token-Grabber#usage).
