### ISSUE TITLE
stops at converting image , and give error of it

### ISSUE THREAD

**Issue by yash0042** [extatent/Discord-QR-Token-Grabber#5]
The QR code wasn't found or failed to create an image.

Press any key to exit.

**Comment by NickTziavas** [comment]
> The QR code wasn't found or failed to create an image.
> 
> Press any key to exit.

exactly my problem.Extatent please fix.

**Comment by yash0042** [comment]
it has been 3 weeks now

**Comment by NickTziavas** [comment]
> it has been 3 weeks now
> still no reply

yeah

**Comment by maros1337** [comment]
same problem
